import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { ThemeProvider } from '@primer/react';
import { QueryClientProvider } from '@tanstack/react-query';

import "./globals.css";
import queryClient from "@/lib/react-query-client";


const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <QueryClientProvider client={queryClient}>
          <ThemeProvider>
            {children}
          </ThemeProvider>
        </QueryClientProvider>
      </body>
    </html>
  );
}
